remove_list = [
    "The Last of Us Remastered",
    "Journey",
    "The Witcher 3: Wild Hunt - Blood and Wine",
    "Grand Theft Auto V",
    "Demon's Souls (2020 Remake)",
    "Demon's Souls (2020)",
    "Shadow of the Colossus",
    "The Legend of Zelda: A Link Between Worlds",
    "Monster Hunter World: Iceborne",
    "Final Fantasy XIV: Shadowbringers",
    "Minecraft",
    "Xenoblade Chronicles: Definitive Edition",
    "The Legend of Zelda: Majora's Mask 3D",
    "The Witcher 3: Wild Hunt - Hearts of Stone",
    "Diablo III: Ultimate Evil Edition",
    "Odin Sphere Leifthrasir",
    "Bayonetta 1+2 - Switch Collection",
    "Tony Hawk's Pro Skater 1 + 2",
    "World of Warcraft: Legion",
    "Guacamelee! Super Turbo Championship Edition",
    "Tales from the Borderlands: Episode Five - The Vault of the Traveler",
    "Ikaruga",
    "Okami HD",
    "Diablo III: Eternal Collection",
    "Rez Infinite",
    "XCOM 2: War of the Chosen",
    "Fez",
    "Bastion",
    "Final Fantasy XIV: Stormblood",
    "Dark Souls II: Scholar of the First Sin",
    "Atari 50: The Anniversary Celebration",
    "Persona 4 Golden",
    "Bayonetta 1+2",
    

    "Final Fantasy XIV: Endwalker",
    "The Stanley Parable: Ultra Deluxe",
    "Cuphead: The Delicious Last Course",
    "The Last of Us Part I",
    "Destiny 2: The Witch Queen",
    "Uncharted: Legacy of Thieves Collection",
    "Quake (2021 Remaster)",
    "Mass Effect Legendary Edition",
    "Streets Of Rage 4 - Mr. X Nightmare",
    "Monster Hunter Rise: Sunbreak",
    "The Nioh Collection",
    "Doki Doki Literature Club Plus!",
    "Dead Space (Remake)",
    "Dead Space (2023)",
    "Metroid Prime Remastered",
    "Resident Evil 4 VR",
    "Dead Cells: Fatal Falls",
    "Dead Cells: Return to Castlevania",
    "Final Fantasy VI Pixel Remaster",
    "Final Fantasy IV Pixel Remaster",
    "Quake",
    "Ghost Trick: Phantom Detective",
    "Streets of Rage 4: Mr. X Nightmare",
    "Quake II",
    "Cyberpunk 2077: Phantom Liberty",
    "Resident Evil 4: Separate Ways",
    "Persona 3 Reload",
    "Braid: Anniversary Edition",
    "Paper Mario: The Thousand-Year Door",
    "Grand Theft Auto IV",
    "Destiny 2: The Final Shape",
    "Elden Ring: Shadow of the Erdtree",
    "Castlevania Dominus Collection",
    "Marvel vs. Capcom Fighting Collection: Arcade Classics",
    "The Talos Principle: Reawakened",
    "Hades II"                                  # <------ Remove this once it leaves Early Access
]

corrections_dict = {
    "Persona 5" : ["Persona 5", "2016"],
    "Persona 5 Royal" : ["Persona 5", "2016"],
    "Mario Kart 8 Deluxe" : ["Mario Kart 8", "2014"],
    "Dragon Quest XI S: Echoes of an Elusive Age - Definitive Edition" : ["Dragon Quest XI: Echoes of an Elusive Age", "2017"],
    "Nier: Automata" : ["NieR: Automata", "2017"],
    "NieR: Automata Become as Gods Edition" : ["NieR: Automata", "2017"],
    "Nier: Automata - The End of YoRHa Edition" : ["NieR: Automata", "2017"],
    "DUSK" : ["DUSK", "2018"],
    "Tetris Effect: Connected" : ["Tetris Effect", "2018"],
    "Ori and the Blind Forest: Definitive Edition" : ["Ori and the Blind Forest", "2015"],
    "Shovel Knight: Treasure Trove" : ["Shovel Knight", "2014"],
    "Mortal Kombat 11 Ultimate" : ["Mortal Kombat 11", "2019"],
    "Marvel's Spider-Man: Remastered" : ["Marvel's Spider-Man", "2018"],
    "Death Stranding Director's Cut" : ["Death Stranding", "2019"],
    "Ghost of Tsushima Director's Cut" : ["Ghost of Tsushima", "2020"],
    "Super Mario 3D World + Bowser's Fury" : ["Super Mario 3D World", "2013"],
    "Disco Elysium: The Final Cut" : ["Disco Elysium", "2019"],
    "Final Fantasy VII Remake Intergrade" : ["Final Fantasy VII Remake", "2020"],
    "Divinity: Original Sin 2 - Definitive Edition" : ["Divinity: Original Sin 2", "2017"],
    "Divinity: Original Sin - Enhanced Edition" : ["Divinity Original Sin", "2014"],
    "Sid Meier's Civilization VI - Console Edition" : ["Sid Meier's Civilization VI", "2016"],
    "Tales from the Borderlands - Season One" : ["Tale from the Borderlands", "2015"],
    "Overcooked! All You Can Eat" : ["Overcooked", "2016"],
    "Street Fighter V: Arcade Edition" : ["Street Fighter V", "2016"],
    "The Last of Us Part II Remastered" : ["The Last of Us Part II", "2020"],
    "Horizon Forbidden West Complete Edition" : ["Horizon Forbidden West", "2022"],
    "Shin Megami Tensei V: Vengeance" : ["Shin Megami Tensei V", "2021"]
}
